Go lume
chaostreff-flensburg/hacks-on-the-harbour-web pull request #23
Opened 2023-10-24 20:19 UTC by Torge

Ich habe das Projekt jetzt auf lume umgezogen und mich dabei ein wenig an der ccs website orientiert.
Es sollte noch alles gleich aussehen, es fehlt jedoch noch die rakeden Animation, die würde ich dann noch irgendwann bauen.

2023-10-25 11:39 UTC, supermomme commented
Die Font muss noch eingebunden werden und die ics-Datei kann man noch nicht herunterladen.

2023-10-25 11:41 UTC, supermomme requested changes
Die Font muss noch eingebunden werden und die ics-Datei kann man noch nicht herunterladen.

2023-10-25 13:48 UTC, supermomme approved these changes

2023-10-26 21:05 UTC, adb-sh approved these changes
nicely done :D where are my rockets? :( (i need that `await new Promise` !!!!)

2023-11-14 17:45 UTC, Torge commented
Die Raketen Animation ist jetzt auch auf der neuen Seite, aber mit canvas und requestAnimationFrame. Das ist so am performantesten von meinen Versuchen.
Der Start/Stop Button ist auch wieder drin.

2024-05-28 19:44 UTC, merged